name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Deny
        run: |
          pushd vmm/sandbox && cargo install cargo-deny && cargo deny -L debug --all-features check && popd
          pushd vmm/task && cargo deny -L debug --all-features check && popd
          pushd shim && cargo deny -L debug --all-features check && popd
          pushd wasm && cargo deny -L debug --all-features check && popd
          pushd quark && cargo deny -L debug --all-features check && popd
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install WasmEdge
        run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.11.2 >> /dev/null
      - name: Check
        run: |
          pushd vmm/sandbox && cargo check --examples --tests --all-features && popd
          pushd vmm/task && cargo check --examples --tests --all-features && popd
          pushd shim && cargo check --examples --tests --all-features && popd
          pushd wasm && cargo check --examples --tests --features=wasmedge && popd
          pushd wasm && cargo check --examples --tests --features=wasmtime && popd
          pushd quark && cargo check --examples --tests --all-features && popd
      - name: Nightly fmt
        run: |
          rustup toolchain install nightly --component rustfmt
          pushd vmm/sandbox && cargo +nightly fmt --all -- --check --files-with-diff && popd
          pushd vmm/task && cargo +nightly fmt --all -- --check --files-with-diff && popd
          pushd shim && cargo +nightly fmt --all -- --check --files-with-diff && popd
          pushd wasm && cargo +nightly fmt --all -- --check --files-with-diff && popd
          pushd quark && cargo +nightly fmt --all -- --check --files-with-diff && popd
      - name: Clippy
        run: |
          pushd vmm/sandbox && cargo clippy --all-features -- -D warnings && popd
          pushd vmm/task && cargo clippy --all-features -- -D warnings && popd
          pushd shim && cargo clippy --all-features -- -D warnings && popd
          pushd wasm && cargo clippy --features=wasmedge -- -D warnings && popd
          pushd wasm && cargo clippy --features=wasmtime -- -D warnings && popd
          pushd quark && cargo clippy --all-features -- -D warnings && popd
  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install WasmEdge
        run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.11.2 >> /dev/null
      - name: Test
        run: |
          pushd vmm/sandbox && sudo -E $(command -v cargo) test --all-features && popd
          pushd vmm/task && sudo -E $(command -v cargo) test --all-features && popd
          pushd shim && sudo -E $(command -v cargo) test --all-features && popd
          pushd wasm && sudo -E $(command -v cargo) test --features=wasmedge && popd
          pushd wasm && sudo -E $(command -v cargo) test --features=wasmtime && popd
          pushd quark && sudo -E $(command -v cargo) test --all-features && popd
